In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from supabase import create_client
import pandas as pd
from dotenv import load_dotenv
from src.config import (
    APPT_NAME, # "Appointment"
    CATEGORY_NAME, # "Category"
    FEATURES_NAME, # "Features"
    FEEDBACK_NAME # "Feedback"
)

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_NONPROD_URL")
SUPABASE_KEY = os.getenv("SUPABASE_NONPROD_PUBLIC_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

### This table contains the appointments freshly extracted from a google sheet for a late predictor project

In [2]:
aapt_res = (
    supabase
    .table(APPT_NAME)
    .select("*")
    .execute()
)

appt_df = pd.DataFrame(aapt_res.data)

appt_df

,appt_id,date,meeting_time,arrived_time,meeting_location,meeting_lat,meeting_lon,category_id
0,f1216142-f3c8-44a6-8e38-ef9638ac760c,2026-01-02,2026-01-02T03:00:00+00:00,2026-01-02T03:07:00+00:00,uncle kkm (bukit panjang),1.377073,103.764559,9612203c-c9b4-4a3a-b477-5c60f1b82f3f
1,7833aa35-95a2-47e6-abef-0a0d2f7d1c77,2026-01-03,2026-01-03T01:15:00+00:00,2026-01-03T01:20:00+00:00,virtual,NaN,NaN,d6721248-554d-4743-8b08-23efa70a0e39
2,1557c133-d5a2-4fa3-a9e6-42112112a215,2026-01-06,2026-01-06T11:30:00+00:00,2026-01-06T12:05:00+00:00,bbdc,1.367094,103.750257,3d4ac6cf-ec85-4f3f-aa82-a872dd7db419
3,ac7b6a2e-ff87-43e0-ac05-0477300de09e,2026-01-08,2026-01-08T11:00:00+00:00,2026-01-08T11:48:00+00:00,raffles place,1.284434,103.849791,3a63ba2d-7b65-4733-b028-29a11f39e560
4,ed99e153-d53f-4f92-98f2-c6891d068977,2026-01-15,2026-01-15T11:00:00+00:00,2026-01-15T11:20:00+00:00,imm,1.336120,103.747071,3a63ba2d-7b65-4733-b028-29a11f39e560
5,cffdbb64-ab80-4071-b92b-e421d7eeae71,2026-01-23,2026-01-23T12:00:00+00:00,2026-01-23T13:00:00+00:00,cck,1.384942,103.744580,3a63ba2d-7b65-4733-b028-29a11f39e560
6,78918c28-8f65-49ba-b3f6-621bdfe5f17e,2026-03-08,2026-03-08T01:20:00+00:00,2026-03-08T01:30:00+00:00,uncle kkm (bukit panjang),1.377073,103.764559,8cfa45b0-df03-4e1c-b7d6-d5ceb1e84812
7,56d12948-9f9c-439b-ade9-365801777b48,2026-03-27,2026-03-27T12:00:00+00:00,2026-03-27T12:15:00+00:00,her house,NaN,NaN,3a63ba2d-7b65-4733-b028-29a11f39e560
8,31bb5125-6fe9-49fc-91a6-6191543f721a,2026-03-28,2026-03-28T07:00:00+00:00,2026-03-28T07:30:00+00:00,suntec,1.295264,103.858294,541fd00f-93f5-466a-927e-b6fec7d578d0
9,229114f8-84e9-47a7-9c32-a2e32b246e68,2026-04-10,2026-04-10T10:30:00+00:00,2026-04-10T10:39:00+00:00,suntec,1.295264,103.858294,3a63ba2d-7b65-4733-b028-29a11f39e560
10,a207df16-cbff-41f2-baa4-8b793ec2d1e6,2026-04-17,2026-04-17T04:45:00+00:00,2026-04-17T04:58:00+00:00,uncle kkm (bukit panjang),1.377073,103.764559,9612203c-c9b4-4a3a-b477-5c60f1b82f3f
11,720d01f7-33d7-4424-b3eb-1ce3bde75dc7,2026-04-28,2026-04-28T02:00:00+00:00,2026-04-28T02:17:00+00:00,jurong east mrt,1.333056,103.742401,9612203c-c9b4-4a3a-b477-5c60f1b82f3f
12,d3cecaf7-0e18-4fa9-8aac-9a89a23b8c4b,2026-05-08,2026-05-08T11:00:00+00:00,2026-05-08T11:21:00+00:00,senja hawker centre,1.387082,103.760789,3a63ba2d-7b65-4733-b028-29a11f39e560
13,8e442d6d-7c2d-4ed5-ac60-0d4dabb46ab0,2026-05-13,2026-05-13T01:45:00+00:00,2026-05-13T01:50:00+00:00,bukit panjang,1.378382,103.762465,8cfa45b0-df03-4e1c-b7d6-d5ceb1e84812

### This table contains the categories of appointments

In [3]:
category_res = (
    supabase
    .table(CATEGORY_NAME)
    .select("*")
    .execute()
)

category_df = pd.DataFrame(category_res.data)

category_df

                            category_id          category
0  9612203c-c9b4-4a3a-b477-5c60f1b82f3f             lunch
1  d6721248-554d-4743-8b08-23efa70a0e39         apply job
2  3d4ac6cf-ec85-4f3f-aa82-a872dd7db419          exercise
3  3a63ba2d-7b65-4733-b028-29a11f39e560     dinner/drinks
4  8cfa45b0-df03-4e1c-b7d6-d5ceb1e84812         breakfast
5  541fd00f-93f5-466a-927e-b6fec7d578d0  work/career fair
6  c1d30e77-fa5d-49b2-87c6-5124e2e8508e            others

### This table contains the features that were used for model training and inferencing

In [4]:
feature_res = (
    supabase
    .table(FEATURES_NAME)
    .select("*")
    .execute()
)

feature_df = pd.DataFrame(feature_res.data)

feature_df

,feature_id,day_of_week,time_of_day,distance_km,category,late_duration_min,appt_id
0,d352fd9a-0cab-4193-a24f-a67161282d41,4,morning,1.274747,lunch,7,f1216142-f3c8-44a6-8e38-ef9638ac760c
1,562f498d-ae74-4f52-9fa6-d0350977036d,1,evening,1.773078,exercise,35,1557c133-d5a2-4fa3-a9e6-42112112a215
2,dc89be6f-e85d-472c-8bd2-5b900afdadad,3,evening,15.205063,dinner/drinks,48,ac7b6a2e-ff87-43e0-ac05-0477300de09e
3,f162b938-26ad-4820-bf22-883a58db832c,3,evening,5.219792,dinner/drinks,20,ed99e153-d53f-4f92-98f2-c6891d068977
4,d9a0fd41-364d-49d7-87f9-f405b7a55f21,4,evening,1.130494,dinner/drinks,60,cffdbb64-ab80-4071-b92b-e421d7eeae71
5,7d7118bf-3b33-4144-ade2-0c9e8d1075f4,6,morning,1.274747,breakfast,10,78918c28-8f65-49ba-b3f6-621bdfe5f17e
6,19292d16-69f7-42bc-a25b-4303231cc48f,5,afternoon,15.077114,work/career fair,30,31bb5125-6fe9-49fc-91a6-6191543f721a
7,93fb814d-883d-4944-9c90-489086674067,4,evening,15.077114,dinner/drinks,9,229114f8-84e9-47a7-9c32-a2e32b246e68
8,894a135d-050c-4622-be5a-07a5bef3778c,4,afternoon,1.274747,lunch,13,a207df16-cbff-41f2-baa4-8b793ec2d1e6
9,1973d813-9e8b-446e-a209-5c1ee008986c,1,morning,5.656470,lunch,17,720d01f7-33d7-4424-b3eb-1ce3bde75dc7
10,b1aeb8e9-9334-4319-a3e0-5af5f12e9ce5,4,evening,0.871136,dinner/drinks,21,d3cecaf7-0e18-4fa9-8aac-9a89a23b8c4b
11,8374f877-c29f-46f4-b11b-ba5b71a1f312,2,morning,1.001013,breakfast,5,8e442d6d-7c2d-4ed5-ac60-0d4dabb46ab0

### This table contains the feedback data provided by users after inferencing was made

In [5]:
feedback_res = (
    supabase
    .table(FEEDBACK_NAME)
    .select("*")
    .execute()
)

feedback_df = pd.DataFrame(feedback_res.data)

feedback_df

Empty DataFrame
Columns: []
Index: []